#!/bin/sh
# Run a command in the app's development environment.

set -e

appdir=$(cd $(dirname "$0")/.. && pwd)
[ -f /etc/inside-container ] && exec "$@"

cmd="$@"; [ "$#" -eq 0 ] && cmd=bash
image=${DOCKER_IMAGE:={{ app_name }}}

exec docker run -it -p {{ port }}:{{ port }} -v "$appdir:/{{ app_name }}" $image $cmd
